#!/bin/bash

# Just a wrapper to ssh to establish X connection to the machine without
# caring about keys and authentication

MACHINE="mininet-1"
PPATH=".vagrant/machines/$MACHINE"
PROVIDER=`ls -1 $PPATH`
PORT=22

if [ ! -f $PPATH/$PROVIDER/port ]; then
	PORT=`vagrant port | grep -e '=> [0-9]*' -oh|cut -c4-`
	OUT="$PPATH/$PROVIDER/port"
	echo $PORT | tee $OUT
	echo "ssh-keygen -R '[127.0.0.1]:'$PORT"
else
	PORT=`cat $PPATH/$PROVIDER/port`
fi


echo ssh vagrant@127.0.0.1 -p $PORT -i $PPATH/$PROVIDER/private_key -X -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null\
	-oLogLevel=FATAL -oCompression=yes -oDSAAuthentication=yes -oIdentitiesOnly=yes\
	$@
